name = "gleither"
version = "2.2.1"

description = "A small data-structure for representing an Either Monad"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "gleither" }
links = []

[dependencies]
gleam_stdlib = "~> 0.36 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
testament = ">= 0.1.1 and < 1.0.0"

[javascript]
typescript_declarations = true

[go-over]
global = true
outdated = true

